server {
    listen      127.0.0.1:8080
    server_name localhost

    root        www/html
    index       index.html
    allow_methods   GET POST
    client_max_body_size 5242880
    autoindex       off
    error_page  404 /errors/404.html

    location /redirect {
        return /index.html
    }

    location /html {
        allow_methods   GET
        root            www/html
        autoindex       off
    }

    location /uploads {
        allow_methods   GET POST DELETE
        root            www/uploads
        autoindex       on
        upload_store    www/uploads
    }

    location /list {
        allow_methods   GET
        root            www/list
        autoindex       on
    }

    location /cgi-bin {
        allow_methods   GET POST
        root            www/cgi-bin
        cgi_pass        .py    /usr/bin/python3
        cgi_pass        .pl    /usr/bin/perl
        cgi_pass        .sh    /usr/bin/bash
    }


}

server {
    listen      127.0.0.1:8081
    server_name localhost

    root        www/8081
    index       index.html
    allow_methods   GET POST
    client_max_body_size 1048576
    upload_store    www/8081/uploads
}
