server {
    listen      127.0.0.1:8080
    server_name localhost
    root        www/html
    index       index.html
}

server {
    listen      127.0.0.1:8080
    server_name other
    root        www/8081
    index       index.html
}
