server {
    listen      127.0.0.1:8082
    listen      127.0.0.1:8083
    server_name localhost

    root        www/html
    index       index.html
    allow_methods   GET
    autoindex       off
    error_page  404 /errors/404.html
}
