server {
    listen      127.0.0.1:8084
    server_name localhost

    root        www/html
    index       index.html
    allow_methods   GET
    autoindex       off

    location /noindex {
        allow_methods   GET
        root            www/noindex
        autoindex       off
    }
}
